### ISSUE TITLE
[Bug] 开启 clash meta 时如果电脑未连接到网络就会回环

### ISSUE THREAD

**Issue by LikeJson** [MetaCubeX/Clash.Meta#604]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.4

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mode: rule
mixed-port: 7890
allow-lan: false
log-level: info
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
```

### Clash log

```shell
部分 log


time="2023-06-05T12:49:26.2592678+08:00" level=info msg="Start initial configuration in progress"
time="2023-06-05T12:49:26.2592678+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2023-06-05T12:49:26.2652326+08:00" level=info msg="Start initial GeoIP rule CN => DIRECT, records: 11824"
time="2023-06-05T12:49:26.2714532+08:00" level=info msg="Initial configuration complete, total time: 12ms"
time="2023-06-05T12:49:26.2734579+08:00" level=info msg="Sniffer is closed"
time="2023-06-05T12:49:26.2734579+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2023-06-05T12:49:26.2734579+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2023-06-05T12:49:26.276465+08:00" level=warning msg="Tun listener get error: no route to internet"
time="2023-06-05T12:49:26.5406611+08:00" level=info msg="[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: gVisor"
```

引用规则
```
time="2023-06-05T12:49:26.5694575+08:00" level=info msg="Start initial provider point"
time="2023-06-05T12:49:26.5700141+08:00" level=info msg="Start initial compatible provider PROXY"
time="2023-06-05T12:49:26.5700141+08:00" level=info msg="Start initial compatible provider default"
time="2023-06-05T12:49:26.7128967+08:00" level=info msg="Start initial provider direct"
time="2023-06-05T12:49:26.7128967+08:00" level=info msg="Start initial provider tld-not-cn"
time="2023-06-05T12:49:26.7136142+08:00" level=info msg="Start initial provider apple"
time="2023-06-05T12:49:26.7136142+08:00" level=info msg="Start initial provider applications"
time="2023-06-05T12:49:26.7136142+08:00" level=info msg="Start initial provider lancidr"
time="2023-06-05T12:49:26.7136142+08:00" level=info msg="Start initial provider cncidr"
time="2023-06-05T12:49:26.7136142+08:00" level=info msg="Start initial provider reject"
time="2023-06-05T12:49:26.7136142+08:00" level=info msg="Start initial provider telegramcidr"
time="2023-06-05T12:49:26.7152001+08:00" level=info msg="Start initial provider private"
time="2023-06-05T12:49:26.7157075+08:00" level=info msg="Start initial provider greatfire"
time="2023-06-05T12:49:26.7157075+08:00" level=info msg="Start initial provider google"
time="2023-06-05T12:49:26.7194239+08:00" level=info msg="Start initial provider steam"
time="2023-06-05T12:49:26.7194239+08:00" level=info msg="Start initial provider gfw"
time="2023-06-05T12:49:26.7194239+08:00" level=info msg="Start initial provider icloud"
time="2023-06-05T12:49:26.7194239+08:00" level=info msg="Start initial provider proxy"
```

一大堆 `level=warning msg="Tun listener get error: no route to internet"`

回环部分
```
time="2023-06-05T12:49:33.1787651+08:00" level=debug msg="[Rule] use default rules"
time="2023-06-05T12:49:33.1851124+08:00" level=debug msg="[DNS] resolve something.example.com from udp://8.8.8.8:53"
time="2023-06-05T12:49:33.1851124+08:00" level=debug msg="[DNS] resolve something.example.com from udp://223.5.5.5:53"
time="2023-06-05T12:49:33.1851124+08:00" level=debug msg="[DNS] resolve something.example.com from udp://114.114.114.114:53"
time="2023-06-05T12:49:33.1856506+08:00" level=debug msg="[DNS] hijack udp:8.8.8.8:53 from 198.18.0.1:51332"
time="2023-06-05T12:49:33.1856506+08:00" level=debug msg="[DNS] hijack udp:114.114.114.114:53 from 198.18.0.1:51334"
time="2023-06-05T12:49:33.1856506+08:00" level=debug msg="[DNS] hijack udp:223.5.5.5:53 from 198.18.0.1:51333"
time="2023-06-05T12:49:33.1856506+08:00" level=debug msg="[DNS] something.example.com --> [], from udp://8.8.8.8:53"
time="2023-06-05T12:49:33.1856506+08:00" level=debug msg="[DNS] something.example.com --> [], from udp://114.114.114.114:53"
time="2023-06-05T12:49:33.1856506+08:00" level=debug msg="[DNS] something.example.com --> [], from udp://223.5.5.5:53"
time="2023-06-05T12:49:33.1862059+08:00" level=debug msg="[DNS] response msg empty: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0xff7e, Response:true, Opcode:0, Authoritative:true, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:\"something.example.com.\", Qtype:0x1c, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}"
time="2023-06-05T12:49:33.1862059+08:00" level=debug msg="[DNS] something.example.com --> 198.18.0.11"
time="2023-06-05T12:49:33.1862059+08:00" level=debug msg="[DNS] resolve something.example.com from udp://8.8.8.8:53"
time="2023-06-05T12:49:33.1862059+08:00" level=debug msg="[DNS] resolve something.example.com from udp://223.5.5.5:53"
time="2023-06-05T12:49:33.1862059+08:00" level=debug msg="[DNS] resolve something.example.com from udp://114.114.114.114:53"
time="2023-06-05T12:49:33.1867383+08:00" level=debug msg="[DNS] hijack udp:8.8.8.8:53 from 198.18.0.1:51335"
time="2023-06-05T12:49:33.1867383+08:00" level=debug msg="[DNS] hijack udp:223.5.5.5:53 from 198.18.0.1:51336"
time="2023-06-05T12:49:33.1867383+08:00" level=debug msg="[DNS] hijack udp:114.114.114.114:53 from 198.18.0.1:51337"
time="2023-06-05T12:49:33.1867383+08:00" level=debug msg="[DNS] something.example.com --> [], from udp://8.8.8.8:53"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] something.example.com --> [], from udp://223.5.5.5:53"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] response msg empty: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x4dde, Response:true, Opcode:0, Authoritative:true, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:\"something.example.com.\", Qtype:0x1c, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] something.example.com --> 198.18.0.11"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] something.example.com --> 198.18.0.11"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] something.example.com --> 198.18.0.11"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] resolve something.example.com from udp://223.5.5.5:53"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] something.example.com --> 198.18.0.11"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] resolve something.example.com from udp://114.114.114.114:53"
time="2023-06-05T12:49:33.1872609+08:00" level=debug msg="[DNS] resolve something.example.com from udp://8.8.8.8:53"
time="2023-06-05T12:49:33.1877883+08:00" level=info msg="[TCP] 198.18.0.1:64024(clash-meta.exe) --> something.example.com:37811 match RuleSet(lancidr) using DIRECT"

```
```


### Description

![image](https://github.com/MetaCubeX/Clash.Meta/assets/85022954/05e39ff3-4ca6-4c54-99c6-6af50fec0536)

**Comment by xishang0128** [comment]
这是预期行为,你没有可用接口给clash出站使用,请确保至少有一个可用的出站接口再开启clash

**Comment by cleanery2022** [comment]
![image](https://github.com/MetaCubeX/Clash.Meta/assets/21093249/0f5bacc5-2e0f-4e3d-8491-15b611a4e775)
![image](https://github.com/MetaCubeX/Clash.Meta/assets/21093249/b08d7ad6-16ce-445f-aac1-65951f97fafd)

建议使用任务计划控制开机自启

**Comment by xz-dev** [comment]
中途断网也会这样，所以用服务控制长期来看是不可行的
我直接加一行规则解决 :)
```
  - PROCESS-NAME,clash-meta,REJECT
```
