### ISSUE TITLE
[Bug] Clash Meta alpha-7aae781 的自带的 GLOBAL 只能读取 proxies 下面的节点信息，并不能读取 use 下的 provider1 、2 等 

### ISSUE THREAD

**Issue by fscarmen** [MetaCubeX/Clash.Meta#626]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-7aae781 

### Clash config

```yaml
######### 锚点 start #######
# proxy 相关
#pr: &pr {type: select, proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,DIRECT]}

#这里是订阅更新和延迟测试相关的
p: &p {type: http, interval: 3600, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}

use: &use
  type: select
  use:
  - provider1
  - provider2

######### 锚点 end #######


# url 里填写自己的订阅,名称不能重复,path（文件位置）不能重复
proxy-providers:
  provider1:
    <<: *p
    url: "https://link.jscdn.cn/1drv/aHR0cHM6Ly8XXXXXXXXXXXXXTXVRYlhnVVBjR0xvcFRkX0szVHBT"
    path: ./proxy_providers/config.yaml

  provider2:
    <<: *p
    url: "https://sub.abc.com/sub?target=clash&new_name=true&url=https%3A%2F%2Frender.baipiaocf.ml&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini"
    path: ./proxy_providers/render.yaml

mode: rule
ipv6: true
log-level: info
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true

external-controller: 0.0.0.0:9090
#external-ui: ui
secret: ""

geodata-mode: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: engage.cloudflareclient.com
  #   port: 2408
  #   ip: "172.16.0.2/32"
  #   ipv6: "2606::1/128"        # 自行替换
  #   private-key: "private-key" # 自行替换
  #   public-key: "public-key"   # 自行替换
  #   udp: true
  #   reserved: "abba"           # 自行替换
  #   mtu: 1280
  #   dialer-proxy: "dns"
  #   remote-dns-resolve: true
  #   dns:
  #     - https://dns.cloudflare.com/dns-query

proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 自动选择, DIRECT], <<: *use }

  - {name: ♻️ 自动选择, <<: *use, tolerance: 20, type: url-test}

#  - {name: ♻️ 自动选择, type: url-test, url: http://www.gstatic.com/generate_204, interval: 300, tolerance: 50, proxies: [♻️ 自动选择, DIRECT, 全部节点]}

  - {name: 🌍 国外媒体, type: select, proxies: [🚀 节点选择, ♻️ 自动选择, 🎯 全球直连], <<: *use }

  - {name: 📲 电报信息, type: select, proxies: [🚀 节点选择, ♻️ 自动选择, 🎯 全球直连], <<: *use }

  - {name: Ⓜ️ 微软服务, type: select, proxies: [🚀 节点选择, 🎯 全球直连], <<: *use }

  - {name: 🌼 ChatGPT, type: select, proxies: [DIRECT, 🚀 节点选择], <<: *use }

  - {name: 🍎 苹果服务, type: select, proxies: [🚀 节点选择, 🎯 全球直连], <<: *use }
  
  - {name: 🎯 全球直连, type: select, proxies: [🚀 节点选择, ♻️ 自动选择], <<: *use }

  - {name: 🛑 全球拦截, type: select, proxies: [REJECT, DIRECT]}

  - {name: 🍃 应用净化, type: select, proxies: [REJECT, DIRECT]}

  - {name: 🐟 漏网之鱼, type: select, proxies: [🚀 节点选择, ♻️ 自动选择, 🎯 全球直连], <<: *use }

  - {name: 🌐 全局模式, type: select, proxies: [DIRECT, 🚀 节点选择, ♻️ 自动选择, 🎯 全球直连], <<: *use }

#  - {name: 默认, type: select, proxies: [DIRECT, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, 全部节点, 自动选择]}
#
#  # - {name: dns, type: select, proxies: [DIRECT, WARP, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, 全部节点, 自动选择]}  # 加入 WARP
#  - {name: dns, type: select, proxies: [DIRECT, 自动选择, 默认, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, 全部节点]}
#
#  - {name: Google, <<: *pr}
#
#  - {name: Telegram, <<: *pr}
#
#  - {name: Twitter, <<: *pr}
#
#  - {name: pixiv, <<: *pr}
#
#  - {name: ehentai, <<: *pr}
#
#  - {name: 哔哩哔哩, <<: *pr}
#
#  - {name: 哔哩哔哩 api, <<: *pr}
#
#  - {name: 哔哩东南亚, <<: *pr}
#
#  - {name: 巴哈姆特, <<: *pr}
#
#  - {name: YouTube, <<: *pr}
#
#  - {name: NETFLIX, <<: *pr}
#
#  - {name: Spotify, <<: *pr}
#
#  - {name: github, <<: *pr}
#
#  - {name: 国内, type: select, proxies: [DIRECT, 默认, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, 全部节点, 自动选择]}
#
#  - {name: 其他, <<: *pr}
#
##分隔,下面是地区分组
#  - {name: 香港, <<: *use,filter: "(?i)港|hk|hongkong|hong kong"}
#
#  - {name: 台湾, <<: *use, filter: "(?i)台|tw|taiwan"}
#
#  - {name: 日本, <<: *use, filter: "(?i)日本|jp|japan"}
#
#  - {name: 美国, <<: *use, filter: "(?i)美|us|unitedstates|united states"}
#
#  - {name: 新加坡, <<: *use, filter: "(?i)(新|sg|singapore)"}
#
#  - {name: 其它地区, <<: *use, filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"}
#
#  - {name: 全部节点, <<: *use }
#

rules:
 - DOMAIN-SUFFIX,openai.com,🌼 ChatGPT
 - DOMAIN,education.github.com,🎯 全球直连
# - DOMAIN-SUFFIX,oracle.com,🎯 全球直连
# - DOMAIN-SUFFIX,oraclecloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连
 - DOMAIN-SUFFIX,ip6-localhost,🎯 全球直连
 - DOMAIN-SUFFIX,ip6-loopback,🎯 全球直连
 - DOMAIN-SUFFIX,local,🎯 全球直连
 - DOMAIN-SUFFIX,localhost,🎯 全球直连
 - IP-CIDR6,fc00::/7,🎯 全球直连,no-resolve
 - IP-CIDR6,fe80::/10,🎯 全球直连,no-resolve
 - IP-CIDR6,fd00::/8,🎯 全球直连,no-resolve
 - DOMAIN,router.asus.com,🎯 全球直连
 - DOMAIN-SUFFIX,hiwifi.com,🎯 全球直连
 - DOMAIN-SUFFIX,leike.cc,🎯 全球直连
 - DOMAIN-SUFFIX,miwifi.com,🎯 全球直连
 - DOMAIN-SUFFIX,my.router,🎯 全球直连
 - DOMAIN-SUFFIX,p.to,🎯 全球直连
 - DOMAIN-SUFFIX,peiluyou.com,🎯 全球直连
 - DOMAIN-SUFFIX,phicomm.me,🎯 全球直连
 - DOMAIN-SUFFIX,routerlogin.com,🎯 全球直连
 - DOMAIN-SUFFIX,tendawifi.com,🎯 全球直连
 - DOMAIN-SUFFIX,zte.home,🎯 全球直连
 - DOMAIN-KEYWORD,admarvel,🛑 全球拦截
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
```
```


### Clash log

_No response_

### Description

这样就导致在 全局界面 下不能选定某个节点。现在曲线的处理办法是多弄个叫“全局模式”的自定义策略组，用 `<<: *use` 这样放上所有的节点，再在GLOBAL 下选这个“全局模式”策略，再对应下面的某个节点。

<img width="914" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/62703343/80f028a5-ea69-42ba-9ff6-df152148a7f9">

**Comment by fscarmen** [comment]
![image](https://github.com/MetaCubeX/Clash.Meta/assets/62703343/95da15f5-f08d-41ad-b60d-2af6ff1fcb77)

**Comment by Skyxim** [comment]
设计如此 provider 不属于 proxy，global 只会引入节点和策略组

**Comment by xishang0128** [comment]
@fscarmen 本来就不行

**Comment by fscarmen2** [comment]
谢谢各位及时的解答，我换个思路，能不能在proxies下用 use 里的provider1，2的全部节点，这样也行，不过我试了一下不行，不知道是格式不对还是原本就不支持的。
