### ISSUE TITLE
[Bug] TUIC-Meta Server 偶尔会突然失联

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/Clash.Meta#676]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-7632827 linux amd64 with go1.21rc3 Thu Jul 20 15:28:17 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
log-level: debug
mode: rule
ipv6: true
tcp-concurrent: true
sniffer:
  enable: false
tuic-server:
  enable: true
  listen: :23333
  token:
    - 
  certificate: 
  private-key: 
  congestion-controller: bbr
  alpn:
    - h3
  authentication-timeout: 5000
  max-idle-time: 15000
```
```


### Clash log

```shell
客户端log
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7775 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7772 --> auth.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match GeoSite/github) 10.10.10.1:7774 --> alive.github.com:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7775 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7770 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7770 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7775 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7773 --> api.termius.com:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match GeoSite/github) 10.10.10.1:7774 --> alive.github.com:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7770 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match GeoSite/google) 10.10.10.1:7771 --> clients4.google.com:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7772 --> auth.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7775 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout
23-07-31 01:12:00[ warn ][TCP] dial PROXY (match Match/) 10.10.10.1:7770 --> sdk.split.io:443 error: Application error 0xfffffff2 (remote): AuthenticationTimeout



服务端log
time="2023-07-31T01:12:05.76044131+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:05.76376007+08:00" level=debug msg="[DNS] x1.c.lencr.org --> 125.252.219.104"
time="2023-07-31T01:12:05.769065785+08:00" level=info msg="[TCP] 脱敏:61705 --> x1.c.lencr.org:80 match Match using DIRECT"
time="2023-07-31T01:12:05.832213635+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:05.835121413+08:00" level=debug msg="[DNS] x2.c.lencr.org --> 125.252.219.104"
time="2023-07-31T01:12:05.839684662+08:00" level=info msg="[TCP] 脱敏:61705 --> x2.c.lencr.org:80 match Match using DIRECT"
time="2023-07-31T01:12:10.72557764+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:10.72639445+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:10.728214563+08:00" level=info msg="[TCP] 脱敏:61705 --> 91.108.56.131:443 match Match using DIRECT"
time="2023-07-31T01:12:10.728853441+08:00" level=info msg="[TCP] 脱敏:61705 --> 91.108.56.131:80 match Match using DIRECT"
time="2023-07-31T01:12:51.196180582+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:51.196235484+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:51.196237566+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:51.199628129+08:00" level=debug msg="[DNS] www.google.com.hk --> 172.253.118.94"
time="2023-07-31T01:12:51.199865316+08:00" level=debug msg="[DNS] alive.github.com --> 140.82.112.25"
time="2023-07-31T01:12:51.200899693+08:00" level=debug msg="[DNS] auth.split.io --> 44.197.221.236"
time="2023-07-31T01:12:51.203483025+08:00" level=info msg="[TCP] 脱敏:44973 --> www.google.com.hk:443 match Match using DIRECT"
time="2023-07-31T01:12:51.413145925+08:00" level=info msg="[TCP] 脱敏:44973 --> auth.split.io:443 match Match using DIRECT"
time="2023-07-31T01:12:51.417759959+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:51.420969256+08:00" level=debug msg="[DNS] sdk.split.io --> 151.101.131.9"
time="2023-07-31T01:12:51.42531854+08:00" level=info msg="[TCP] 脱敏:44973 --> sdk.split.io:443 match Match using DIRECT"
time="2023-07-31T01:12:51.437879755+08:00" level=info msg="[TCP] 脱敏:44973 --> alive.github.com:443 match Match using DIRECT"
time="2023-07-31T01:12:52.589955783+08:00" level=debug msg="[Rule] use default rules"
time="2023-07-31T01:12:52.593251572+08:00" level=debug msg="[DNS] streaming.split.io --> 52.84.251.32"
time="2023-07-31T01:12:52.597063466+08:00" level=info msg="[TCP] 脱敏:44973 --> streaming.split.io:443 match Match using DIRECT"
```

### Description

使用一段时间后，会突然连不上外网，客户端报错error: Application error 0xfffffff2 (remote): AuthenticationTimeout，突然性故障，不一定能稳定复现，双端均为最新alpha (commits 7632827)，十几分钟后恢复正常

**Comment by ShoukakuChuuCC** [comment]
我发现我用的还是TUIC V4，换成V5观察一段时间看看还会不会出现

**Comment by ArchGuyWu** [comment]
> 我发现我用的还是TUIC V4，换成V5观察一段时间看看还会不会出现

看起来像是断流了

**Comment by ShoukakuChuuCC** [comment]
> > 我发现我用的还是TUIC V4，换成V5观察一段时间看看还会不会出现
> 
> 看起来像是断流了

不是，我分别搭建有TUIC和Trojan，就TUIC协议会突然失联，TUIC失联时，Trojan协议在Yacd面板测试还是通的
